model_config:
  vilbert:
    training_head_type: classification
    num_labels: 2
    losses:
    - type: cross_entropy

  
 
    
    

dataset_config:
  csi:
    fast_read: false
    #data_dir: ${env.data_dir}
    data_dir: /data/csi_videos/
    #data_folder: /data/csi_videos/
    use_images: false
    use_features: true
    features:
      train:
      - features_csi_organisers.lmdb
      #- features_csi_lmdb.lmdb
      val:
      - features_csi_organisers.lmdb
      #- features_csi_lmdb.lmdb
      
      test:
      - features_csi_organisers.lmdb
      #- features_csi_lmdb.lmdb
      
    annotations:
      train:
      - vilbert_text_files/dialogue_train_0.csv
      #- csi/dialogue.csv
      val:
      - vilbert_text_files/dialogue_dev_0.csv
      # - csi/dialogue.csv
      test:
      - vilbert_text_files/dialogue_test_0.csv
      # - csi/dialogue.csv
      

    return_features_info: true
    processors:
      text_processor:
        type: bert_tokenizer
        params:
          tokenizer_config:
            type: bert-base-uncased
            params:
              do_lower_case: true
          mask_probability: 0
          max_seq_length: 512
      transformer_bbox_processor:
        type: transformer_bbox
        params:
          bbox_key: boxes
          image_width_key: image_w
          image_height_key: image_h
          
      #answer_processor:
        #type: multi_class_from_file
        #params:
            #num_answers: 1
            #vocab_file: datasets/mmimdb/defaults/extras/classes_mm_imdb.txt
            #preprocessor:
                #type: simple_word
                #params: {}
        #type: prediction.argmax
          


optimizer:
  type: adam_w
  params:
    lr: 1e-5
    #lr: 0.001
    eps: 1e-8

scheduler:
  type: warmup_linear
  params:
    num_warmup_steps: 2000
    num_training_steps: ${training.max_updates}

evaluation:
  metrics: 
  - accuracy
  - binary_f1
  predict: false
 

training:
  batch_size: 2
  seed: 1
  lr_scheduler: true
  # Don't forget to update schedule_attributes if you update this
  max_updates: 3000
  device: cuda
  find_unused_parameters: true
  val_check_interval: 100
  early_stop:
    criteria: csi/binary_f1
    minimize: false

checkpoint:
  max_to_keep: 3
  pretrained_state_mapping:
    model.bert: model.bert
