

mmf_run config=projects/visual_bert/configs/csi/defaults.yaml    model=visual_bert    dataset=csi    run_type=train_val_test checkpoint.resume_pretrained=True checkpoint.resume_zoo=visual_bert.finetuned.mmimdb.direct dataset_config.csi.annotations.train=/data/csi_videos/vilbert_text_files/nondialogue_train_0.csv  dataset_config.csi.annotations.val=/data/csi_videos/vilbert_text_files/nondialogue_dev_0.csv  dataset_config.csi.annotations.test=/data/csi_videos/vilbert_text_files/nondialogue_test_0.csv   > visual_bert_nondialogue_imdb_10folds_terminal/fold0.txt env.save_dir=./savevisualbert



mmf_run config=projects/visual_bert/configs/csi/defaults.yaml    model=visual_bert    dataset=csi    run_type=train_val_test checkpoint.resume_pretrained=True checkpoint.resume_zoo=visual_bert.finetuned.mmimdb.direct dataset_config.csi.annotations.train=/data/csi_videos/vilbert_text_files/nondialogue_train_1.csv  dataset_config.csi.annotations.val=/data/csi_videos/vilbert_text_files/nondialogue_dev_1.csv  dataset_config.csi.annotations.test=/data/csi_videos/vilbert_text_files/nondialogue_test_1.csv > visual_bert_nondialogue_imdb_10folds_terminal/fold1.txt env.save_dir=./savevisualbert

mmf_run config=projects/visual_bert/configs/csi/defaults.yaml    model=visual_bert    dataset=csi    run_type=train_val_test checkpoint.resume_pretrained=True checkpoint.resume_zoo=visual_bert.finetuned.mmimdb.direct dataset_config.csi.annotations.train=/data/csi_videos/vilbert_text_files/nondialogue_train_2.csv  dataset_config.csi.annotations.val=/data/csi_videos/vilbert_text_files/nondialogue_dev_2.csv  dataset_config.csi.annotations.test=/data/csi_videos/vilbert_text_files/nondialogue_test_2.csv > visual_bert_nondialogue_imdb_10folds_terminal/fold2.txt env.save_dir=./savevisualbert

mmf_run config=projects/visual_bert/configs/csi/defaults.yaml    model=visual_bert    dataset=csi    run_type=train_val_test checkpoint.resume_pretrained=True checkpoint.resume_zoo=visual_bert.finetuned.mmimdb.direct dataset_config.csi.annotations.train=/data/csi_videos/vilbert_text_files/nondialogue_train_3.csv  dataset_config.csi.annotations.val=/data/csi_videos/vilbert_text_files/nondialogue_dev_3.csv  dataset_config.csi.annotations.test=/data/csi_videos/vilbert_text_files/nondialogue_test_3.csv > visual_bert_nondialogue_imdb_10folds_terminal/fold3.txt env.save_dir=./savevisualbert

mmf_run config=projects/visual_bert/configs/csi/defaults.yaml    model=visual_bert    dataset=csi    run_type=train_val_test checkpoint.resume_pretrained=True checkpoint.resume_zoo=visual_bert.finetuned.mmimdb.direct dataset_config.csi.annotations.train=/data/csi_videos/vilbert_text_files/nondialogue_train_4.csv  dataset_config.csi.annotations.val=/data/csi_videos/vilbert_text_files/nondialogue_dev_4.csv  dataset_config.csi.annotations.test=/data/csi_videos/vilbert_text_files/nondialogue_test_4.csv > visual_bert_nondialogue_imdb_10folds_terminal/fold4.txt env.save_dir=./savevisualbert

mmf_run config=projects/visual_bert/configs/csi/defaults.yaml    model=visual_bert    dataset=csi    run_type=train_val_test checkpoint.resume_pretrained=True checkpoint.resume_zoo=visual_bert.finetuned.mmimdb.direct dataset_config.csi.annotations.train=/data/csi_videos/vilbert_text_files/nondialogue_train_5.csv  dataset_config.csi.annotations.val=/data/csi_videos/vilbert_text_files/nondialogue_dev_5.csv  dataset_config.csi.annotations.test=/data/csi_videos/vilbert_text_files/nondialogue_test_5.csv > visual_bert_nondialogue_imdb_10folds_terminal/fold5.txt env.save_dir=./savevisualbert

mmf_run config=projects/visual_bert/configs/csi/defaults.yaml    model=visual_bert    dataset=csi    run_type=train_val_test checkpoint.resume_pretrained=True checkpoint.resume_zoo=visual_bert.finetuned.mmimdb.direct dataset_config.csi.annotations.train=/data/csi_videos/vilbert_text_files/nondialogue_train_6.csv  dataset_config.csi.annotations.val=/data/csi_videos/vilbert_text_files/nondialogue_dev_6.csv  dataset_config.csi.annotations.test=/data/csi_videos/vilbert_text_files/nondialogue_test_6.csv > visual_bert_nondialogue_imdb_10folds_terminal/fold6.txt env.save_dir=./savevisualbert

mmf_run config=projects/visual_bert/configs/csi/defaults.yaml    model=visual_bert    dataset=csi    run_type=train_val_test checkpoint.resume_pretrained=True checkpoint.resume_zoo=visual_bert.finetuned.mmimdb.direct dataset_config.csi.annotations.train=/data/csi_videos/vilbert_text_files/nondialogue_train_7.csv  dataset_config.csi.annotations.val=/data/csi_videos/vilbert_text_files/nondialogue_dev_7.csv  dataset_config.csi.annotations.test=/data/csi_videos/vilbert_text_files/nondialogue_test_7.csv > visual_bert_nondialogue_imdb_10folds_terminal/fold7.txt env.save_dir=./savevisualbert

mmf_run config=projects/visual_bert/configs/csi/defaults.yaml    model=visual_bert    dataset=csi    run_type=train_val_test checkpoint.resume_pretrained=True checkpoint.resume_zoo=visual_bert.finetuned.mmimdb.direct  dataset_config.csi.annotations.train=/data/csi_videos/vilbert_text_files/nondialogue_train_8.csv  dataset_config.csi.annotations.val=/data/csi_videos/vilbert_text_files/nondialogue_dev_8.csv  dataset_config.csi.annotations.test=/data/csi_videos/vilbert_text_files/nondialogue_test_8.csv > visual_bert_nondialogue_imdb_10folds_terminal/fold8.txt env.save_dir=./savevisualbert

mmf_run config=projects/visual_bert/configs/csi/defaults.yaml    model=visual_bert    dataset=csi    run_type=train_val_test checkpoint.resume_pretrained=True checkpoint.resume_zoo=visual_bert.finetuned.mmimdb.direct dataset_config.csi.annotations.train=/data/csi_videos/vilbert_text_files/nondialogue_train_9.csv  dataset_config.csi.annotations.val=/data/csi_videos/vilbert_text_files/nondialogue_dev_9.csv  dataset_config.csi.annotations.test=/data/csi_videos/vilbert_text_files/nondialogue_test_9.csv > visual_bert_nondialogue_imdb_10folds_terminal/fold9.txt env.save_dir=./savevisualbert

